name: "ROCm installer"
description: "Install ROCm"
author: "Leon Oostrum"
inputs:
  version:
    description: "ROCm version to install. Set to either major.minor.patch (e.g. 6.4.0), or 'latest'"
    required: false
    default: "latest"
  usecase:
    description: "Forwarded to the --usecase option of amdgpu-install."
    required: false
    default: "rocmdev,hiplibsdk"
runs:
  using: "Composite"
  steps:
    - name: "Set PATH"
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: "Install AMDGPU installer"
      shell: bash
      run: |
        filename=$(download_amdgpu_installer.sh ${{ inputs.version }})
        sudo apt install ./${filename}
        sudo apt update
    - name: "Install ROCm"
      shell: bash
      run: sudo amdgpu-install --usecase=${{ inputs.usecase }} --no-dkms -y
branding:
  icon: arrow-down-circle
  color: green
