name: "ROCm installer"
description: "Install ROCm"
author: "Leon Oostrum"
inputs:
  version:
    description: "ROCm version to install. Set to either major.minor.patch (e.g. 6.4.0), or 'latest'"
    required: false
    default: "latest"
  usecase:
    description: "Forwarded to the --usecase option of amdgpu-install."
    required: false
  packages:
    description: "Space-separated list of packages to intall."
    required: false
    default: "hipcc hip-dev rocm-device-libs"
runs:
  using: "Composite"
  steps:
    - name: "Set PATH"
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    - name: "Install AMDGPU installer"
      shell: bash
      run: |
        filename=$(download_amdgpu_installer.sh ${{ inputs.version }})
        sudo apt update
        sudo apt install -y ./${filename}
        sudo apt update
    - name: "Install ROCm through amdgpu-install"
      if: "${{ inputs.usecase != '' }}"
      shell: bash
      run: sudo amdgpu-install --usecase=${{ inputs.usecase }} --no-dkms -y
    - name: "Install ROCm packages"
      if: "${{ inputs.packages != '' }}"
      shell: bash
      run: sudo apt install -y ${{ inputs.packages }}
    - name: "Ensure /opt/rocm/bin is in PATH"
      shell: bash
      run: echo /opt/rocm/bin >> $GITHUB_PATH
branding:
  icon: arrow-down-circle
  color: green
