name: "ROCm installer"
description: "Install ROCm"
author: "Leon Oostrum"
inputs:
  version:
    description: "ROCm version to install"
    required: false
    default: "6.4.0"
runs:
  using: "Composite"
  steps:
    - name: "Install AMDGPU installer"
      shell: bash
      run: |
        source /etc/os-release
        wget https://repo.radeon.com/amdgpu-install/6.4/ubuntu/${VERSION_CODENAME}/amdgpu-install_6.4.60400-1_all.deb
        sudo apt install ./amdgpu-install_6.4.60400-1_all.deb
        sudo apt update
    - name: "Install ROCm"
      shell: bash
      run: sudo amdgpu-install --rocmrelease=${{ inputs.version }}  --usecase=rocmdev,hiplibsdk --no-dkms -y
