name: "ROCm installer"
description: "Install ROCm"
author: "Leon Oostrum"
inputs:
  version:
    description: "ROCm version to install"
    required: false
    default: "6.4"
runs:
  using: "Composite"
  steps:
    - name: "Install AMDGPU installer"
      run: |
        wget https://repo.radeon.com/amdgpu-install/6.4/ubuntu/jammy/amdgpu-install_6.4.60400-1_all.deb
        sudo apt install ./amdgpu-install_6.4.60400-1_all.deb
        sudo apt update
    - name: "Install ROCm"
      run: sudo amdgpu-install --rocmrelease=${{ inputs.version }}  --usecase=rocmdev,hiplibsdk --no-dkms -y
    - name: "Add ROCm to PATH"
      run: "echo /opt/rocm/bin >> $GITHUB_PATH"
